/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.banking;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

public class Account {
    ArrayList<String> bankStatementRegister = new ArrayList();
    Integer moneyStored = 0;
    String statementString = "Date              Amount        Balance\n";


    public void deposit(Integer money) {
        // deposita na conta
        depositMoneyInAccount(money);
        statementRegister(money);
    }

    private void depositMoneyInAccount(Integer money) {
        if (money < 0) {
            log("You can't deposit negative values");
        } else {
            moneyStored =+ money;
        }

    }

    String getDateFormated() {
        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        return dateFormat.format(date);
    }

    public void withDraw(Integer money) {
        if (moneyStored >= money) {
            moneyStored += money;
            statementRegister(money);
        } else {
            log("You don't have this amount of money!");
        }
    }

    public String printStatement() {
        if (!bankStatementRegister.isEmpty()) {
            bankStatementRegister.forEach( s -> {
                log("\nConcating statementString: \n" + statementString.concat(s) + "\n");
                statementString += s + "\n";
            });
        }
        return statementString;
    }


    public String statementRegister(Integer depositMoney) {
        // Statement format:
        // Date        Amount  Balance
        //24.12.2015   +500      500
        String statement = getDateFormated();
        statement += "        " + getMoneyPrefix(depositMoney) + "" + depositMoney;
        statement += "             " + getMoneyStored();
        log("\nSaving New Statement: ");
        log("Date              Amount        Balance\n" + statement);

        bankStatementRegister.add(statement);
        return statement;
    }

    private String getMoneyPrefix(Integer depositMoney) {
        String prefixMoney = "";
        if (depositMoney > 0)
            prefixMoney = "+";
        return prefixMoney;
    }

    public String getMoneyStored() {
        return moneyStored.toString();
    }

    private void log(String logString) {
        System.out.println(logString);
    }
}
