/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.banking;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AccountTest {

    public static final String BASIC_STATEMENT_STRING = "Date              Amount        Balance\n";

    @Test
    public void shouldDepositAndStoreMoneyCorrectly() {
        //GIVEN
        Account account = new Account();
        Integer money = 500;

        //WHEN
        account.deposit(money);

        //THEN
        assert(account.getMoneyStored().equals(money.toString()));
    }

    @Test
    public void printStatementShouldBeBasicStringWhenWeDontHaveMoneyInAccount() {
        //GIVEN
        Account account = new Account();

        //WHEN
        String printStatement = account.printStatement();

        //THEN
        assert(printStatement.equals(BASIC_STATEMENT_STRING));
    }

    @Test
    public void printStatementShouldReturnNonEmptyStringWhenWeHaveSomeMoneyInAccount() {
        //GIVEN
        Account account = new Account();
        Integer money = 500;
        account.deposit(money);
        Integer money2 = -100;
        account.withDraw(money2);
        String dateFormated = account.getDateFormated();
        String expectedStatement =
                BASIC_STATEMENT_STRING +
                dateFormated + "        +500             500\n" +
                dateFormated + "        -100             400";

        //WHEN
        String statement = account.printStatement();
        Integer sum = money + money2;
        String sumString = sum.toString();

        //THEN
        assert(statement.contains(expectedStatement));
        assertEquals(account.getMoneyStored(), sumString);
    }

    @Test
    public void withDrawShouldBeDoneCorrectly() {
        // GIVEN
        Account account = new Account();
        account.deposit(100);

        // WHEN
        account.withDraw(100);

        // THEN
        assertEquals(account.getMoneyStored(), Integer.toString(0));
    }

    @Test
    public void withDrawWithEnoughResources() {
        //GIVEN
        Account account = new Account();
        account.deposit(100);
        String dateFormated = account.getDateFormated();
        String expectedStatement =
                BASIC_STATEMENT_STRING +
                        dateFormated + "        +100             100";

        //WHEN
        account.withDraw(200);
        String statement = account.printStatement();

        //THEN
        assertEquals(account.getMoneyStored(), Integer.toString(100));
        assert(statement.contains(expectedStatement));
    }

}
