/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.banking;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AccountTest {
    @Test void testSomeLibraryMethod() {
        Account classUnderTest = new Account();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
